### ISSUE TITLE
Special Handling for Cargo deps with paths?

### ISSUE THREAD

**Issue by Pat-Lafon** [zshipko/ocaml-rust-starter#7]
Hello, not sure if this is an issue with Dune or with the rule this template repo uses to grab the compiled rust files.

I've been playing around with template and I wanted to add a Rust dependency to my cargo file which is only local, not published on crates.io. 

The change to the cargo.toml dependency looks like this `arwen_synth = {version = "0.1.0", path = "../../Github/Arwen_Synth"}`.

I think the "../.." causes an issue because the error I get looks like:

```
File "src/dune", line 1, characters 0-464:
 1 | (rule
 2 |  (targets libmy_project.a dllmy_project.so)
 3 |  (deps
....
13 |     mv
14 |     %{project_root}/../../target/release/libmy_project.a
15 |     libmy_project.a))))
error: failed to get `arwen_synth` as a dependency of package `my_project v0.1.0 (~/Desktop/tmp/ocaml-rust-starter/_build/default)`

Caused by:
  failed to load source for dependency `arwen_synth`

Caused by:
  Unable to update ~/Desktop/tmp/ocaml-rust-starter/Github/Arwen_Synth

Caused by:
  failed to read `~/Desktop/tmp/ocaml-rust-starter/Github/Arwen_Synth/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Note, I would expect it to try to read from `~/Desktop/Github/Arwen_Synth/Cargo.toml` which is what Cargo does.

Do you have any suggestions?

**Comment by zshipko** [comment]
I have just opened this PR: https://github.com/zshipko/ocaml-rust-starter/pull/8 - does it fix the issue for you?

In general getting these builds right takes some trial and error since `cargo` and `dune` both have specfic file structures that don't exactly play well together.

**Comment by Pat-Lafon** [comment]
As commented on that pr, this fix worked for me. Having only lightly used `dune` before this, I have found its style pretty different to cargo's making things seem a bit fragile.
